- - Dishsoap
  - NA2
  - NA
  - GDtO4yJ1GG0b4C4S2zxqxUhdcPju_rmtGnsVVzNdvbOG0XRrh2bo2g3ekCC-eyXJVNC9B8kKkXe33g
- - M8 Jedusor
  - '12345'
  - EUW
  - kOsBya31_nrnKb4zXBoXJa9IKnMz9JIa8i_Dyxf6bMvXy5GzuFYDoxtiVrtWMpAV1CKLOjQf4fkkgQ
- - eusouolucas
  - '1111'
  - BR1
  - w8vSvHzPK4lcrlnqQWlQ2JNH36xqf0CIbHhBYV-n-H8x2gtwC8djiK1stYmFgfTh8sXSCNfrLKOnXw
- - Deis1k
  - EUW
  - EUW
  - Nc13EOew5HOm8epkuLLehYTMHEwP0QIWVH1MWWwloCqAozwfZi1vuRxWCwPxEHIgvDPf6IvT-ZumxA
- - "S\xF3 bio"
  - BR1
  - BR
  - F35MREp64IcD2bSekqk89rON6qkzdD_BnEEL7T5XBn4ZYC7JzzwQrd-tOb1dKf2kEzjSOxNrkpTJlg
- - VIT prestivent
  - '123'
  - NA
  - XXSIWM79xLgJeyY0bn8bFnDBC1vcqZJVr6l2UUX9pyqFgQzyc3Xiw184sLGatcXJE25ZfQdN1AC3cg
- - RCS Xperion
  - EUW11
  - EUW
  - o3OEd_6rmOKd1HqpFksDtihgpgy1JNXOx8DI7kO5HrJf-LLsKFadRDnT5fDRM2IbhccbL37w7pTkVQ
- - MIH TarteMan
  - EUW
  - EUW
  - vY0cq71fLXi9sQbTZjkDzeWacza-Ku3Y-1K8poEx5QsfhptbtnR7llzjYjh-MJfWdlVWodrY3fNhRA
- - "\uAC15\uC120\uC885"
  - KR123
  - KR
  - 'Error fetching riot id: 404'
- - Boomhae
  - 0901
  - SEA
  - cXgVs5Lha9SqCMQb65Kuum9Uk7-WizwffHyslrnRRAcYGI0qlG9smSeyKAWnd_V6b1p4nF1JpqPnuw
- - "\uBE48 \uD2C8"
  - '123'
  - KR
  - WZoTjjJHQNgWjO4aydENeJT9Euo1VFSv-o00YWcesFCu1_EV8FUzjFVTeMm9BAi5o1RQS00yIadDlA
- - META SpencerTFT
  - TFT
  - NA
  - CzOmt0D3kLzljvMUZ8_VqSnHU1HdqSw3qzsL1R7GZchfEwcLWOeRLzctXRTL82a4jwRTX_dJjHaN1g
